### ISSUE TITLE
Tela Financeiro - Alunos

### ISSUE THREAD

**Issue by rivanbello** [tahnamao/fael-manager#27]
GESTOR | Tela "Financeiro"
- [ ] `GET /payments`
  - [ ] Filtros
    - [ ] Vendedores vs. Alunos
    - [ ] TEXT Nome
    - [ ] TEXT Valor
    - [ ] DATERANGE Data
    - [ ] ENUM "Não Pagas" | "Pendentes" | "Pagas"
  - [ ] Paginação (cursor)
- [ ] PUT /seller-payment-status
- [ ] POST /student-payment

**Comment by DAWestphal** [comment]
falta requisição @rivanbello
